version: '2'
services:
  jenkins:
    build: .
    ports:
     - "2222:2222"
     - "8080:8080"
     - "8081:8081"
     - "9418:9418"
    depends_on:
     - sonarqube
  sonarqube:
    image: sonarqube:6.3
    ports:
     - "9000:9000"
     - "9092:9092"
